name: CI
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        npm i --prod-only --no-audit
        npm run build
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: dist
        repo: wherehaveibeen/wherehaveibeen.github.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}