name: CI
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        npm i --prod-only --no-audit
        npm run build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: dist
        CLEAN: true
        REPOSITORY_NAME: wherehaveibeen/wherehaveibeen.github.io
        GIT_CONFIG_NAME: ${{ secrets.GIT_USERNAME }}
        GIT_CONFIG_EMAIL: ${{ secrets.GIT_EMAIL }}
