name: CI
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        npm i --prod-only --no-audit
        npm run build
    - name: Deploy to GitHub Pages
      uses: appleboy/gh-pages-action@v0.0.2
      with:
        username: SplinterHead
        password: ${{ secrets.ACCESS_TOKEN }}
        remote_url: https://github.com/wherehaveibeen/wherehaveibeen.github.io
        target_branch: master
        pages_directory: dist
        commit_author: SplinterHead
        commit_author_email: lewis2004@hotmail.com
